name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Build
        id: build
        shell: bash
        env:
          _TAG: ${{ github.ref }}
        run: |
          .\build.bat
          git fetch -a
          tag="$(git describe --tags --abbrev=0)"
          release_name="winapiexec-${tag}"

          # Pack files
          7z a -tzip "${release_name}-x86.zip" "./Release/winapiexec.exe"
          7z a -tzip "${release_name}-x64.zip" "./x64/Release/winapiexec.exe"

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Publish
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "*.zip"
          tag_name: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          draft: false
          prerelease: false
