name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Build
        run: .\build.bat

      - name: Zip
        id: zip
        shell: bash
        run: |
          git fetch -a
          tag="$(git describe --tags --abbrev=0)"
          echo "::set-output name=LATEST_TAG::${tag}"

          release_name="winapiexec-${tag}"

          7z a -tzip "${release_name}-x86.zip" "./Release/winapiexec.exe"
          7z a -tzip "${release_name}-x64.zip" "./x64/Release/winapiexec.exe"

      - name: Publish
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "*.zip"
          tag_name: ${{ steps.zip.outputs.LATEST_TAG }}
          draft: false
          prerelease: false
